version: '3'
services:
  supplier:
    image: anouerkassaa/devops_indiv:latest
    build: .
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8085:8085"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - my-network
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  sonarqube:
    image: sonarqube
    container_name: sonar
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extensions:/opt/SonarQube/extensions'
      - 'SonarQube_Logs:/opt/SonarQube/logs'
    networks:
      - my-network
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - 'nexus-data:/nexus-data'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_Logs:
  nexus-data:
  db:
  .m2: